import {useEffect, useState} from 'react'
import Head from 'next/head'
import styles from '../styles/Home.module.css'
import {create} from '@tdf-labs/the-data-faucet-sdk'
import { JsonViewer } from '@textea/json-viewer'

const dataFaucet = create({url: 'https://graph.tdf-labs.io/latest/graphql'});

export default function Home() {
  const [data, setData] = useState<any>();

  useEffect(() => {
    async function queryData() {
      setData(null);
      const data = await dataFaucet.query.chain.polkadot.balanceTransfers({
        address: "13GgtddFytMGMZApWQbr8y45j1kGM4LAsLEtX1zx4sgmKhZv",
      });
      setData(data);
    }

    queryData().catch((error) => {console.log('Query error :::: ', error)})
  }, [])

  return (
    <div className={styles.container}>
      <Head>
        <title>TDF sdk playground</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        {Boolean(data) ? <JsonViewer rootName='data' enableClipboard={false} value={data}/> : null}
      </main>

      {/* <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer> */}
    </div>
  )
}
